### ISSUE TITLE
API queries with expired access tokens should trigger a refresh token flow

### ISSUE THREAD

**Issue by chownces** [CS3219-AY2324S1/ay2324s1-course-assessment-g20#22]
Implement the refresh token flow in the frontend:
- Access token expires
- Case 1 (refresh token valid):
  - POST refresh token to backend refresh token endpoint '/v1/auth/refresh'
  - If error occurs, log user out in the frontend, else
  - Receive new set of JWT tokens
  - Store new tokens in local storage
- Case 2 (refresh token invalid):
  - Refresh token has also expired
  - Log user out in the frontend

NOTE:
- If the user is in the middle of firing an API request when his access token has expired, do the refresh flow before automatically retrying the request again
- If the user is in the middle of firing MULTIPLE API requests when his access token expires, do the refresh flow ONCE before retrying all the failed API requests again

**Comment by kwokieee** [comment]
Closed via #65
