### ISSUE TITLE
N11: Implement an API gateway to redirect requests to the relevant microservices

### ISSUE THREAD

**Issue by chownces** [CS3219-AY2324S1/ay2324s1-course-assessment-g20#42]
N11: The application should have an API gateway of some kind that redirects requests to the
relevant microservices. An example would be using an ingress controller such as NGINX ingress
controller if using Kubernetes (https://kubernetes.GitHub.io/ingress-nginx/).

**Comment by kwokieee** [comment]
Closed via #50
