### ISSUE TITLE
N7: Users should be able to query LLMs to seek explanation of code written by the other user in a collaborative session

### ISSUE THREAD

**Issue by chownces** [CS3219-AY2324S1/ay2324s1-course-assessment-g20#44]
N7: Incorporate generative AI to assist during the preparation. For example, users can seek help from ChatGPT, Copilot (or such other services) to seek explanation of code written by the other participant. Users can seek help from gen AI to solve the puzzle by providing prompts from within the interface.

**Comment by kwokieee** [comment]
Closed via #79
