### ISSUE TITLE
Users should be able to view question title, description, category, difficulty

### ISSUE THREAD

**Issue by BryannYeap** [CS3219-AY2324S1/ay2324s1-course-assessment-g20#7]
Desktop:
![image](https://github.com/CS3219-AY2324S1/ay2324s1-course-assessment-g20/assets/77266823/95d69939-d5c0-4745-84db-1a9fca68eabd)

Mobile:
![image](https://github.com/CS3219-AY2324S1/ay2324s1-course-assessment-g20/assets/77266823/a095348e-09aa-43ca-915e-8cec1f136617)

**Comment by kwokieee** [comment]
Closed via #64
